services:
  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: aymanesbe3/projetpda-backend
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - laravel_storage:/var/www/storage/app/public
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"  # Laravel backend
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - laravel_storage:/var/www/storage/app/public
    depends_on:
      - backend

  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: aymanesbe3/projetpda-frontend
    container_name: react_app
    working_dir: /app
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # React frontend
    stdin_open: true
    tty: true

  react-native-cli:
    # build:
    #   context: ./frontendMobile
    #   dockerfile: Dockerfile
    image: aymanesbe3/projetpda-frontendmobile
    container_name: react_native_cli
    working_dir: /app
    volumes:
      - ./frontendMobile:/app
      - /app/node_modules
    ports:
      - "8082:8081"  # Metro Bundler (optionnel)
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"  # phpMyAdmin interface
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Redis server

volumes:
  mysql_data:
  laravel_storage: